/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#dad7ff",
        "on-secondary-fixed": "#141b2b",
        "on-primary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#444749",
        "inverse-surface": "#2a313d",
        "inverse-primary": "#c3c0ff",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed": "#e1e2e4",
        "surface-container": "#e7eefe",
        error: "#ba1a1a",
        "on-surface-variant": "#464555",
        "tertiary-container": "#5e6062",
        "on-primary-fixed": "#0f0069",
        tertiary: "#46484a",
        "on-tertiary-container": "#dadbdd",
        "on-primary-fixed-variant": "#3323cc",
        "surface-variant": "#dce2f3",
        "on-surface": "#151c27",
        "inverse-on-surface": "#ebf1ff",
        outline: "#777587",
        "on-error": "#ffffff",
        "on-secondary-container": "#5c6274",
        "on-secondary-fixed-variant": "#404758",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#4d44e3",
        background: "#f9f9ff",
        "surface-container-highest": "#dce2f3",
        "secondary-fixed": "#dce2f7",
        "secondary-container": "#d9dff5",
        "on-secondary": "#ffffff",
        "primary-container": "#4f46e5",
        "surface-dim": "#d3daea",
        primary: "#3525cd",
        secondary: "#575e70",
        "surface-container-low": "#f0f3ff",
        "surface-container-high": "#e2e8f8",
        "surface-bright": "#f9f9ff",
        "primary-fixed": "#e2dfff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#c5c6c8",
        "on-background": "#151c27",
        "secondary-fixed-dim": "#c0c6db",
        "on-tertiary-fixed": "#191c1e",
        "on-error-container": "#93000a",
        surface: "#f9f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "40px",
        "stack-sm": "12px",
        gutter: "16px",
        base: "8px",
        "container-margin": "20px",
        "stack-md": "24px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "fare-display": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "fare-display": [
          "24px",
          { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "700" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
