// Mirrors the `colors` tokens in tailwind.config.js. NativeWind resolves
// `className` colors for View/Text/Image/Pressable/ScrollView/TextInput
// automatically, but third-party components (e.g. @expo/vector-icons) take
// `color` as a plain prop, so those call sites import this map instead.
export const themeColors = {
  onPrimaryContainer: "#dad7ff",
  onSecondaryFixed: "#141b2b",
  onPrimary: "#ffffff",
  outlineVariant: "#c7c4d8",
  errorContainer: "#ffdad6",
  onTertiaryFixedVariant: "#444749",
  inverseSurface: "#2a313d",
  inversePrimary: "#c3c0ff",
  primaryFixedDim: "#c3c0ff",
  tertiaryFixed: "#e1e2e4",
  surfaceContainer: "#e7eefe",
  error: "#ba1a1a",
  onSurfaceVariant: "#464555",
  tertiaryContainer: "#5e6062",
  onPrimaryFixed: "#0f0069",
  tertiary: "#46484a",
  onTertiaryContainer: "#dadbdd",
  onPrimaryFixedVariant: "#3323cc",
  surfaceVariant: "#dce2f3",
  onSurface: "#151c27",
  inverseOnSurface: "#ebf1ff",
  outline: "#777587",
  onError: "#ffffff",
  onSecondaryContainer: "#5c6274",
  onSecondaryFixedVariant: "#404758",
  surfaceContainerLowest: "#ffffff",
  surfaceTint: "#4d44e3",
  background: "#f9f9ff",
  surfaceContainerHighest: "#dce2f3",
  secondaryFixed: "#dce2f7",
  secondaryContainer: "#d9dff5",
  onSecondary: "#ffffff",
  primaryContainer: "#4f46e5",
  surfaceDim: "#d3daea",
  primary: "#3525cd",
  secondary: "#575e70",
  surfaceContainerLow: "#f0f3ff",
  surfaceContainerHigh: "#e2e8f8",
  surfaceBright: "#f9f9ff",
  primaryFixed: "#e2dfff",
  onTertiary: "#ffffff",
  tertiaryFixedDim: "#c5c6c8",
  onBackground: "#151c27",
  secondaryFixedDim: "#c0c6db",
  onTertiaryFixed: "#191c1e",
  onErrorContainer: "#93000a",
  surface: "#f9f9ff",
} as const;
