import type { ScreenInfo, UserFormData } from "./types";

export const SCREENS_INFO: ScreenInfo[] = [
  {
    id: "phone-verification",
    stepNumber: 1,
    totalSteps: 15,
    title: "1. Phone Number (Let's Get Started)",
    category: "Verification",
  },
  {
    id: "enter-code",
    stepNumber: 2,
    totalSteps: 15,
    title: "2. Enter Code (OTP Verification)",
    category: "Verification",
  },
  {
    id: "who-is-profile-for",
    stepNumber: 3,
    totalSteps: 15,
    title: "3. Who Is Profile For?",
    category: "Profile Setup",
  },
  {
    id: "gender",
    stepNumber: 4,
    totalSteps: 15,
    title: "4. Gender Selection",
    category: "Profile Setup",
  },
  {
    id: "basic-details",
    stepNumber: 5,
    totalSteps: 15,
    title: "5. Basic Details & DOB",
    category: "Personal Info",
  },
  {
    id: "what-looking-for",
    stepNumber: 6,
    totalSteps: 15,
    title: "6. What Are You Looking For?",
    category: "Intent & Timeline",
  },
  {
    id: "education-work",
    stepNumber: 7,
    totalSteps: 15,
    title: "7. Education & Work Location",
    category: "Background",
  },
  {
    id: "demographics",
    stepNumber: 8,
    totalSteps: 15,
    title: "8. Demographics & Household",
    category: "Background",
  },
  {
    id: "lifestyle-interests",
    stepNumber: 9,
    totalSteps: 15,
    title: "9. Lifestyle & Interests",
    category: "Lifestyle",
  },
  {
    id: "family-background",
    stepNumber: 10,
    totalSteps: 15,
    title: "10. Family Background",
    category: "Family",
  },
  {
    id: "add-photos",
    stepNumber: 11,
    totalSteps: 15,
    title: "11. Add Photos",
    category: "Media",
  },
  {
    id: "community-promise",
    stepNumber: 12,
    totalSteps: 15,
    title: "12. Community Promise",
    category: "Guidelines",
  },
  {
    id: "verification",
    stepNumber: 13,
    totalSteps: 15,
    title: "13. Identity Verification (Verify It's Really You)",
    category: "Security",
  },
  {
    id: "choose-plan",
    stepNumber: 14,
    totalSteps: 15,
    title: "14. Choose How You Search (Plans)",
    category: "Membership",
  },
  {
    id: "profile-activating",
    stepNumber: 15,
    totalSteps: 15,
    title: "15. Profile Activating (Celebration)",
    category: "Success",
  },
];

export const INITIAL_FORM_DATA: UserFormData = {
  phoneNumber: "0300 1234567",
  otpCode: ["", "", "", "7", "3", "9"],
  profileFor: "myself",
  gender: "female",
  firstName: "Fatima",
  lastName: "Ali",
  maritalStatus: "single",
  religion: "islam",
  dob: "1998-05-14",
  intent: "ready",
  timeline: "4–12 months",
  educationLevel: "bachelors",
  instituteName: "NUST, Islamabad",
  employmentStatus: "employed",
  profession: "engineering",
  country: "pakistan",
  nationality: "pakistani",
  cityState: "Lahore, Punjab",
  heightInches: 66,
  sect: "sunni",
  ethnicity: "urdu",
  caste: "Syed",
  houseSize: "10 Marla, 4 Bedroom",
  incomeBracket: "200_500k",
  religionPractice: "practising",
  eatHalalOnly: true,
  smoke: false,
  drinkAlcohol: false,
  moveAbroad: true,
  haveChildren: false,
  interests: ["Reading", "Travel", "Cooking", "Islamic History"],
  fatherDetails: "Retired Banker",
  motherDetails: "Homemaker",
  brothers: "1",
  sisters: "2",
  familyLocation: "Lahore, Pakistan",
  financialStatus: "high",
  photos: [null, null, null, null, null, null],
  agreedToPromise: true,
  selectedPlan: "standard",
};
